// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.9
//   protoc               unknown
// source: emailverification/v1/email_verification.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "emailverification.v1";

export interface VerifyEmailRequest {
  email: string;
}

export interface VerifyEmailResponse {
  valid: boolean;
  reason?: string | undefined;
  checks?: EmailChecks | undefined;
}

export interface EmailChecks {
  format: boolean;
  mx: boolean;
  disposable: boolean;
}

function createBaseVerifyEmailRequest(): VerifyEmailRequest {
  return { email: "" };
}

export const VerifyEmailRequest: MessageFns<VerifyEmailRequest> = {
  encode(message: VerifyEmailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyEmailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyEmailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyEmailRequest {
    return { email: isSet(object.email) ? globalThis.String(object.email) : "" };
  },

  toJSON(message: VerifyEmailRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyEmailRequest>, I>>(base?: I): VerifyEmailRequest {
    return VerifyEmailRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyEmailRequest>, I>>(object: I): VerifyEmailRequest {
    const message = createBaseVerifyEmailRequest();
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseVerifyEmailResponse(): VerifyEmailResponse {
  return { valid: false, reason: undefined, checks: undefined };
}

export const VerifyEmailResponse: MessageFns<VerifyEmailResponse> = {
  encode(message: VerifyEmailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.valid !== false) {
      writer.uint32(8).bool(message.valid);
    }
    if (message.reason !== undefined) {
      writer.uint32(18).string(message.reason);
    }
    if (message.checks !== undefined) {
      EmailChecks.encode(message.checks, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyEmailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyEmailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.valid = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.checks = EmailChecks.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyEmailResponse {
    return {
      valid: isSet(object.valid) ? globalThis.Boolean(object.valid) : false,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : undefined,
      checks: isSet(object.checks) ? EmailChecks.fromJSON(object.checks) : undefined,
    };
  },

  toJSON(message: VerifyEmailResponse): unknown {
    const obj: any = {};
    if (message.valid !== false) {
      obj.valid = message.valid;
    }
    if (message.reason !== undefined) {
      obj.reason = message.reason;
    }
    if (message.checks !== undefined) {
      obj.checks = EmailChecks.toJSON(message.checks);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyEmailResponse>, I>>(base?: I): VerifyEmailResponse {
    return VerifyEmailResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyEmailResponse>, I>>(object: I): VerifyEmailResponse {
    const message = createBaseVerifyEmailResponse();
    message.valid = object.valid ?? false;
    message.reason = object.reason ?? undefined;
    message.checks = (object.checks !== undefined && object.checks !== null)
      ? EmailChecks.fromPartial(object.checks)
      : undefined;
    return message;
  },
};

function createBaseEmailChecks(): EmailChecks {
  return { format: false, mx: false, disposable: false };
}

export const EmailChecks: MessageFns<EmailChecks> = {
  encode(message: EmailChecks, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.format !== false) {
      writer.uint32(8).bool(message.format);
    }
    if (message.mx !== false) {
      writer.uint32(16).bool(message.mx);
    }
    if (message.disposable !== false) {
      writer.uint32(24).bool(message.disposable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailChecks {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailChecks();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.format = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mx = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.disposable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailChecks {
    return {
      format: isSet(object.format) ? globalThis.Boolean(object.format) : false,
      mx: isSet(object.mx) ? globalThis.Boolean(object.mx) : false,
      disposable: isSet(object.disposable) ? globalThis.Boolean(object.disposable) : false,
    };
  },

  toJSON(message: EmailChecks): unknown {
    const obj: any = {};
    if (message.format !== false) {
      obj.format = message.format;
    }
    if (message.mx !== false) {
      obj.mx = message.mx;
    }
    if (message.disposable !== false) {
      obj.disposable = message.disposable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailChecks>, I>>(base?: I): EmailChecks {
    return EmailChecks.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailChecks>, I>>(object: I): EmailChecks {
    const message = createBaseEmailChecks();
    message.format = object.format ?? false;
    message.mx = object.mx ?? false;
    message.disposable = object.disposable ?? false;
    return message;
  },
};

export type EmailVerificationServiceService = typeof EmailVerificationServiceService;
export const EmailVerificationServiceService = {
  verifyEmail: {
    path: "/emailverification.v1.EmailVerificationService/VerifyEmail" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: VerifyEmailRequest): Buffer => Buffer.from(VerifyEmailRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyEmailRequest => VerifyEmailRequest.decode(value),
    responseSerialize: (value: VerifyEmailResponse): Buffer => Buffer.from(VerifyEmailResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VerifyEmailResponse => VerifyEmailResponse.decode(value),
  },
} as const;

export interface EmailVerificationServiceServer extends UntypedServiceImplementation {
  verifyEmail: handleUnaryCall<VerifyEmailRequest, VerifyEmailResponse>;
}

export interface EmailVerificationServiceClient extends Client {
  verifyEmail(
    request: VerifyEmailRequest,
    callback: (error: ServiceError | null, response: VerifyEmailResponse) => void,
  ): ClientUnaryCall;
  verifyEmail(
    request: VerifyEmailRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VerifyEmailResponse) => void,
  ): ClientUnaryCall;
  verifyEmail(
    request: VerifyEmailRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VerifyEmailResponse) => void,
  ): ClientUnaryCall;
}

export const EmailVerificationServiceClient = makeGenericClientConstructor(
  EmailVerificationServiceService,
  "emailverification.v1.EmailVerificationService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): EmailVerificationServiceClient;
  service: typeof EmailVerificationServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
